general {
  hide_cursor = true
}

background {
  path = ~/Pictures/wallpapers/wallpaper22.jpg
  blur_passes = 3
  noise = 0.0411
  color = rgb(28, 28, 28)
}

label {
  text = cmd[update:100] echo -e "<i>$(date +'%H:%M')</i>"
  font_family = JetBrainsMono Nerd Font Bold
  color = rgb(230, 230, 200)
  font_size = 50
  position = 0, 0
}

label {
  text = cmd[update:500] echo -e "<i>$(date +'%d.%m.%y')</i>"
  color = rgba(230, 230, 200, 0.4)
  font_family = JetBrainsMono Nerd Font Bold
  font_size = 18
  position = 0, 50
}

input-field {
  size = 150, 60
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(68, 133, 136, 0.0)
  inner_color = rgba(30, 30, 30, 0.0)
  font_color = rgba(230, 230, 200, 0.6)
  font_family = JetBrainsMono Nerd Font Bold
  fade_on_empty = false
  fade_timeout = 0
  placeholder_text = <i>Enter</i>
  hide_input = false
  rounding = 0
  check_color = rgba(68, 133, 136, 0.0)
  fail_color = rgba(204, 36, 29, 0.0)
  fail_text = <i>$FAIL</i>
  invert_numlock = false
  position = 0, -50
}
