# Modifiers
$mainMod = SUPER

# Programs
bind = $mainMod SHIFT, RETURN, exec, $terminal
bind = $mainMod SHIFT, R, exec, $browser
bind = $mainMod, W, exec, $file_manager

# Launcher
bind = $mainMod, P, exec, $menu_run
bind = $mainMod SHIFT, P, exec, $menu_drun
# Launcher scripts
bind = $mainMod SHIFT, O, exec, $menu_power
bind = $mainMod, O, exec, $menu_clipboard
bind = $mainMod SHIFT, I, exec, $menu_system
bind = $mainMod, I, exec, $menu_emoji

# Screen
bind = $mainMod, Q, exec, $screenshot_area_copy
bind = $mainMod SHIFT, Q, exec, $screenshot_output_save
bind = $mainMod, X, exec, $color_picker
bind = $mainMod, S, exec, $lockscreen

# Windows
bind = $mainMod SHIFT, C, killactive,
bind = $mainMod SHIFT, M, exit,

bind = $mainMod, V, togglefloating,
bind = $mainMod, A, pin,
bind = $mainMod SHIFT, F, fullscreen,

# Dwindle layout
# bind = $mainMod, D, layoutmsg, swapsplit
# bind = $mainMod SHIFT, D, togglesplit,
# bind = $mainMod SHIFT, F, pseudo,

# Scrolling
bind = $mainMod, period, layoutmsg, move +col
bind = $mainMod, comma, layoutmsg, move -col

bind = $mainMod, bracketleft, layoutmsg, swapcol l
bind = $mainMod, bracketright, layoutmsg, swapcol r

bind = $mainMod, R, layoutmsg, colresize +conf
bind = $mainMod, F, layoutmsg, colresize 1.0

# Signals
bind = $mainMod SHIFT, B, exec, $reload_waybar
bind = $mainMod, B, exec, $toggle_waybar

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
# Cycles all windows (floating and tiled)
bind = $mainMod CTRL, U, cyclenext

# Move window
bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

# Special workspace
bind = $mainMod, E, togglespecialworkspace, magic
bind = $mainMod SHIFT, E, movetoworkspace, special:magic

# Switch through workspaces
# bind = $mainMod, TAB, workspace, r+1
# bind = $mainMod SHIFT, TAB, workspace, r-1

# Move/resize windows (float)
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Resize window (layout)
binde = $mainMod CTRL, L, resizeactive, 50 0
binde = $mainMod CTRL, H, resizeactive, -50 0
binde = $mainMod CTRL, K, resizeactive, 0 -50
binde = $mainMod CTRL, J, resizeactive, 0 50

# Volume management
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness management
# bindel = $mainMod, G, exec, brightnessctl -e4 -n2 set 5%+
# bindel = $mainMod SHIFT, G, exec, brightnessctl -e4 -n2 set 5%-

# Multimedia binds (playerctl)
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

