ecosystem {
  # Permissions
  enforce_permissions = false
  
  # Notifications
  no_donation_nag = true
  no_update_news = true
}

# Default
# permission = .*, plugin, deny # Blocks all other apps from loading plugins

# Programs
# permission = /usr/bin/hyprpicker, screencopy, allow

# permission = /usr/bin/sh, screencopy, allow
# permission = /usr/bin/bash, screencopy, allow
# permission = /usr/bin/zsh, screencopy, allow
# permission = /usr/bin/foot, screencopy, allow

# permission = /usr/bin/hyprshot, screencopy, allow
# permission = /usr/bin/grim, screencopy, allow
# permission = /usr/bin/slurp, screencopy, allow

# permission = /usr/bin/hyprlock, screencopy, allow

# permission = /usr/bin/wl-copy, screencopy, allow
# permission = /usr/bin/cliphist, screencopy, allow

# permission = /usr/bin/obs, screencopy, allow

# Reqiured by Hyprland
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# Plugins
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow # hyprpm plugin manager
