xwayland {
  enabled = true
  force_zero_scaling = true
}

binds {
  hide_special_on_workspace_change = true
  allow_pin_fullscreen = true
}

cursor {
  enable_hyprcursor = true
  inactive_timeout = 60
  no_hardware_cursors = 0
}
