general {
  gaps_in = 3
  gaps_out = 6
  border_size = 3
  col.active_border = rgb(d65d0e) # rgb(9b981f) 45deg
  col.inactive_border = rgb(504945)
  resize_on_border = false
  allow_tearing = true
  layout = scrolling

  snap {
    enabled = true
    window_gap = 0
    monitor_gap = 5
  }
}

scrolling {
  explicit_column_widths = 0.33333, 0.5, 0.66667
}

decoration {
  rounding = 0
  rounding_power = 0

  active_opacity = 1
  inactive_opacity = 1

  shadow {
    enabled = false
    range = 5
    render_power = 3
    color = rgba(1a1a1aff)
    ignore_window = true
  }

  blur {
    enabled = false
    size = 2
    passes = 4
    vibrancy = 0.1
    noise = 0.411

    new_optimizations = true
    special = false
  }
}

animations {
  enabled = true

  # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
  #        NAME,           X0,   Y0,   X1,   Y1
  bezier = easeOutQuint,   0.23, 1,    0.32, 1
  bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
  bezier = linear,         0,    0,    1,    1
  bezier = almostLinear,   0.5,  0.5,  0.75, 1
  bezier = quick,          0.15, 0,    0.1,  1

  # Default animations, see https://wiki.hypr.land/Configuring/Animations/
  #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
  animation = global,        0,     10,    default
  animation = border,        0,     5.39,  easeOutQuint
  animation = windows,       1,     4.79,  easeOutQuint
  animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
  animation = windowsOut,    1,     1.49,  linear,       popin 87%
  animation = fadeIn,        0,     1.73,  almostLinear
  animation = fadeOut,       0,     1.46,  almostLinear
  animation = fade,          0,     3.03,  quick
  animation = layers,        0,     3.81,  easeOutQuint
  animation = layersIn,      0,     4,     easeOutQuint, fade
  animation = layersOut,     0,     1.5,   linear,       fade
  animation = fadeLayersIn,  0,     1.79,  almostLinear
  animation = fadeLayersOut, 0,     1.39,  almostLinear
  animation = workspaces,    0,     3,    almostLinear, fade
  animation = workspacesIn,  0,     0.9,     almostLinear, fade
  animation = workspacesOut, 0,     0.9,     almostLinear, fade
  animation = zoomFactor,    1,     7,     quick
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_on_top = true
  new_status = master
}

misc {
  # disable_autoreload = true

  # Perfomance
  vrr = 0 # 0 - off, 1 - on, 2 - fullscreen only, 3 - fullscreen with video
  vfr = true

  # Other
  middle_click_paste = true
  enable_anr_dialog = false

  # Background
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  background_color = 0x000000
}

render {
  direct_scanout = 2
  new_render_scheduling = true
  expand_undersized_textures = true
}
