# Directories
$PICTURES = ~/Pictures
$MENU_SCRIPTS = ~/.config/fuzzel/scripts-hyprland

# Programs
$terminal = foot
$file_manager = $terminal -e yazi
$browser = librewolf
$bar = waybar -c ~/.config/waybar/hyprland/config-hyprland.jsonc -s ~/.config/waybar/hyprland/style-hyprland.css

# Launcher
$menu_drun = fuzzel --prompt='Launch: '
$menu_run = fuzzel --list-executables-in-path --prompt='Execute: '
$menu_power = $MENU_SCRIPTS/power_menu.sh
$menu_clipboard = $MENU_SCRIPTS/cliphist_menu.sh
$menu_system = $MENU_SCRIPTS/system_menu.sh
$menu_emoji = bemoji

# Daemons
$notify_daemon = dunst
$idle_daemon = hypridle
$wallpaper_daemon = awww-daemon

# Applets
$network_applet = nm-applet
$bluetooth_applet = blueman-applet

# Screen
$screenshot_area_copy = hyprshot -m region -m DVI-I-1 -t 2500 --clipboard-only
$screenshot_output_save = hyprshot -m output -m DVI-I-1 -o $PICTURES/screenshots -t 4000

$color_picker = hyprpicker -a
$lockscreen = hyprlock --no-fade-in

# Signals
$toggle_waybar = killall -SIGUSR1 waybar
$reload_waybar = killall -SIGUSR2 waybar
