# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#   name = no-gaps-wtv1
#   match:float = false
#   match:workspace = w[tv1]

#   border_size = 0
#   rounding = 0
# }

# windowrule {
#   name = no-gaps-f1
#   match:float = false
#   match:workspace = f[1]

#   border_size = 0
#   rounding = 0
# }

windowrule {
  # Ignore maximize requests from all apps. You'll probably like this.
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  # Fix some dragging issues with XWayland
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

windowrule {
  name = pinned-windows-color
  match:float = true
  match:pin = true
  border_color = rgb(d65d0e) rgb(427b58) 
}

# Hyprland-run windowrule
# windowrule {
#     name = move-hyprland-run

#     match:class = hyprland-run

#     move = 20 monitor_h-120
#     float = yes
# }

# blueman-manager
windowrule {
  name = fix-blueman-manager
  match:class = blueman-manager

  float = true
  center = true
  size = 800 500
}

# Choose Files
# windowrule = match:class Choose Files, float true, center true, size 1200 700

# imv
windowrule {
  name = fix-imv
  match:class = imv

  float = true
  center = true
  size = 800 600
}

# nm-connection-editor
windowrule {
  name = fix-nm
  match:class = nm-connection-editor

  float = true
  center = true
  size = 850 500
}

# DDNet
windowrule {
  name = fix-ddnet
  match:class = DDNet

  sync_fullscreen = true
  immediate = true
}

