# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#   name = no-gaps-wtv1
#   match:float = false
#   match:workspace = w[tv1]

#   border_size = 0
#   rounding = 0
# }

# windowrule {
#   name = no-gaps-f1
#   match:float = false
#   match:workspace = f[1]

#   border_size = 0
#   rounding = 0
# }

windowrule {
  # Ignore maximize requests from all apps. You'll probably like this.
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  # Fix some dragging issues with XWayland
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

windowrule {
  # Another color for pinned windows
  name = pinned-windows-color
  match:float = true
  match:pin = true
  border_color = rgb(d65d0e) rgb(427b58) 
}

windowrule {
  # Float windows by title
  name = floating-by-title
  match:title = (Rename "*.*"|File Operation Progress|Confirm to replace files|Attention|Rename file|Choose file|Choose files|Font Manager|Volume Control|Qalculate!|Library|Add bookmark|Bluetooth Devices|Create Document from .*|New .* ...|Create New)
  
  float = on
  center = on
  persistent_size = on
}

windowrule {
  # Float windows by class
  name = floating-by-class
  match:class = (blueman-manager|blueman-services|nwg-look|org.qbittorrent.qBittorrent|kvantummanager|\
               *.*-polkit|nm-connection-editor|qt5ct|mpv|\
               vlc|xdg-desktop-portal-gtk|org.gnome.eog|qt6ct|imv)
  float = on
  center = on
  persistent_size = on
}

# DDNet
windowrule {
  name = fix-ddnet-vsync
  match:class = DDNet

  sync_fullscreen = true
  immediate = true
}

